// Fictional six-beat adaptation; encoded audio samples determine scene boundaries.
export const COMMUNICATION_RECORD_BEATS = [
  {id: "sources", title_fil: "Ihiwalay ang pinagmulan", title_en: "Separate the sources", detail_fil: "Sinabi • nakita • hindi tiyak", detail_en: "Reported • observed • unknown", fil: "Nakinig si Gibs kay Liza at sa kapitbahay. Walang card na naipakita. Iba ang sinabi sa nakita; hindi pa tiyak ang petsa.", en: "Gibs listens to Liza and the neighbor. No card is shown. Reports differ from observations; the date remains uncertain."},
  {id: "relevant-detail", title_fil: "Kaugnay lamang", title_en: "Only relevant details", detail_fil: "Layunin at awtorisadong gamit", detail_en: "Purpose and authorized use", fil: "Ipinaliwanag ni Gibs ang layunin at awtorisadong gamit ng profile. Kaugnay na detalye lamang ang itatala, walang tsismis o pangakong ganap na lihim.", en: "Gibs explains the profile’s purpose and authorized use. He records only relevant details, without gossip or an absolute secrecy promise."},
  {id: "conflicting-accounts", title_fil: "Linawin ang kuwento", title_en: "Clarify the account", detail_fil: "Huwag pumili sa lakas ng boses", detail_en: "Do not choose the loudest voice", fil: "Sabi ni Liza, kinansela ang schedule. Sabi ng kapitbahay, hindi siya interesado. Nagtanong si Gibs kay Liza; hindi siya pumili sa lakas ng boses.", en: "Liza reports cancellation. The neighbor says she is not interested. Gibs asks Liza to clarify rather than choosing the loudest voice."},
  {id: "verify-gap", title_fil: "Iwasto nang tapat", title_en: "Correct honestly", detail_fil: "May pinagmulan ang pagwawasto", detail_en: "Keep the correction’s source", fil: "Nilinaw ni Liza: hindi siya nakapunta nang wala ang kapatid; hindi tiyak ang pagkansela. Itinala ni Gibs ang paglilinaw. Hindi pa nakumpirma ang petsa.", en: "Liza clarifies: she could not attend when her sister was away; cancellation is uncertain. Gibs attributes the correction. The date remains unconfirmed."},
  {id: "practice", title_fil: "Ayusin at subukan", title_en: "Sort and rehearse", detail_fil: "Lahat ay susubok bilang BHW", detail_en: "Everyone attempts the BHW role", fil: "Sa triad, iayos ang source cards, gumawa ng tala at tukuyin ang beripikasyon sa awtorisadong rekord. Mag-feedback, ulitin at magpalit ng papel.", en: "In triads, sort source cards, write a note and name verification through the authorized record. Give feedback, retry and rotate roles."},
  {id: "check", title_fil: "Tapat na tala", title_en: "An honest record", detail_fil: "Buod nakumpirma • petsa hindi pa", detail_en: "Summary confirmed • date still unknown", fil: "Kinumpirma ni Liza ang buod ng sarili niyang sinabi, hindi ang attendance. Ang susunod na hakbang ay beripikasyon kasama ang awtorisadong midwife. Walang hinulaang resulta.", en: "Liza confirms the summary of her own report, not attendance. Next comes verification with the authorized midwife. No result is guessed."},
] as const;
