// Fictional action-planning adaptation. Never a local service commitment.
export const PROBLEM_ACTION_PLAN_BEATS = [
  {id: "compare-solutions", title_fil: "Tumatama ba sa sanhi?", title_en: "Match the cause", detail_fil: "Poster o schedule trial?", detail_en: "Poster or schedule trial?", fil: "Sa kathang-isip na scenario, natiyak ang hadlang sa trabaho at pag-aalaga ng bata. Inihambing ni Carole ang poster at pagtalakay ng maliit na schedule trial.", en: "The fictional scenario supplies verified work and childcare barriers. Carole compares a poster with discussion of a small schedule trial."},
  {id: "plan", title_fil: "Pitong bahagi", title_en: "Seven plan fields", detail_fil: "Hiwalay ang kasunduan", detail_en: "Agreement is separate", fil: "Sanhi, mungkahi, owner, resources, deadline, sukatan at review date. Konsultasyon muna; hinihintay pa ang staff time at trial date.", en: "Cause, proposal, owner, resources, deadline, measure and review date. Consult first; staff time and a trial date remain pending."},
  {id: "partners", title_fil: "Kumpirmahin ang ambag", title_en: "Confirm contributions", detail_fil: "Residente at health team", detail_en: "Residents and health team", fil: "Konsultasyon ang papel ni Carole. Desisyon sa schedule ang sa may tungkuling health team. Isama ang bihirang makadalo; hindi pahintulot ang pananahimik.", en: "Carole handles consultation; the responsible health team decides schedules. Include seldom-heard residents. Silence does not establish agreement."},
  {id: "review", title_fil: "Hindi dumami", title_en: "No increase", detail_fil: "Bago 1/3 · Pagkatapos 1/3", detail_en: "Before 1/3 · After 1/3", fil: "Sa hiwalay na review exercise, may kasunduan sa naunang trial. Isa sa tatlong inimbitahan ang nakadalo bago at pagkatapos. Dalawa pa rin ang hindi nakapunta.", en: "A separate review exercise supplies agreement to an earlier trial. One of three invited households attended before and after. Two still missed visits."},
  {id: "practice", title_fil: "Magtanong at mag-retry", title_en: "Ask and retry", detail_fil: "Feedback → rebisyon", detail_en: "Feedback → revision", fil: "Hindi resulta ang natapos na meeting. Kumustahin muli ang trabaho, gastos, pag-aalaga at abiso. Ipresenta ang plano, sagutin ang katuwang, baguhin at ulitin.", en: "A completed meeting is not an outcome. Recheck work, costs, childcare and notice. Present the plan, answer partner questions, revise and retry."},
  {id: "check", title_fil: "Tapat na mungkahi", title_en: "An honest proposal", detail_fil: "Hinihintay pa ang trial", detail_en: "Trial still pending", fil: "Ibalik ni Carole ang mungkahi sa team. Staff time at trial date ay hinihintay pa. Review ng attendance pagkatapos ng napagkasunduang trial; walang pangakong lutas na.", en: "Carole returns the proposal to the team. Staff time and a trial date remain pending. Review attendance after an agreed trial; do not claim the problem solved."},
] as const;
