// @vitest-environment node
import {describe,it,expect} from 'vitest';import fs from 'node:fs';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {loadReferenceModule,parseReferenceRead,FACILITATOR_SECTION_IDS} from '../lib/reference-content.mjs';import {narrationForLesson} from '../../src/lib/elearning/reference-narration.ts';import {beforeProposed162} from './lesson-162-proposal-compat.mjs';
const leaf='content/training/day1-basic-competencies/modules/06-komunikasyon/lessons/communication-clarify/',j=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const baseline=j('docs/lesson-162-baseline.json'),lesson=j(leaf+'lesson.json'),old=JSON.parse(baseline.target_utf8[leaf+'lesson.json']);
describe('lesson 1.6.2 independent Gibs clarification draft',()=>{
 it('preserves complete identity and old resume meaning in both modes',()=>{expect(lesson.manifest).toEqual(old.manifest);expect(lesson.sections.map(s=>s.id)).toEqual(['open-question','clarify-detail','barriers','confirm-summary','practice','check']);const slides=j(leaf+'slides.json');for(const s of old.sections){expect(lesson.sections.find(n=>n.id===s.id).concept_ids).toEqual(s.concept_ids);expect(slides.find(n=>n.id==='slide-'+s.id).concept_ids).toEqual(s.concept_ids);}expect(lesson.coverage.map(c=>c.id)).toEqual(['m6.clarify','m6.barriers']);});
 it('loads complete paired narration and action art, retaining the approved portrait',()=>{const loaded=loadReferenceModule('content/training/day1-basic-competencies/modules/06-komunikasyon','public').lessons.find(l=>l.manifest.lesson_key==='communication-clarify');for(const lang of ['fil','en']){const read=parseReferenceRead(fs.readFileSync(leaf+'read.'+lang+'.md','utf8'));expect(read).toHaveLength(6);for(const [i,s]of read.entries())expect(loaded.revision.slides[i]['narration_'+lang]).toBe(s.body);}expect(lesson.sections[0].asset_ids).toContain('gibs-portrait');for(const s of lesson.sections){const art=lesson.assets.find(a=>a.id==='clarify-'+s.id);expect(s.asset_ids).toContain(art.id);expect(sha(fs.readFileSync('public'+art.path))).toBe(art.content_hash);expect(art.review_status).toBe('draft');}});
 it('retains the dilemma and every option, explains all choices and confirms a corrected ending',()=>{const c=lesson.sections.at(-1).check;expect(c.options).toEqual(old.sections.at(-1).check.options);expect(c.correct_option_index).toBe(0);for(const w of ['Una:','Ikalawa:','Ikatlo:','Kinumpirma','hindi pa'])expect(c.feedback_fil).toContain(w);for(const w of ['First:','Second:','Third:','confirms','still unconfirmed'])expect(c.feedback_en).toContain(w);});
 it('keeps one bilingual observable indicator and the full 90-minute practice guide',()=>{const rubric=j(leaf+'competency.json').observation_indicators;expect(rubric).toHaveLength(1);expect(rubric[0].objective_index).toBe(0);expect(Object.keys(rubric[0].levels)).toHaveLength(6);for(const l of ['fil','en']){const g=fs.readFileSync(leaf+'facilitator.'+l+'.md','utf8');expect([...g.matchAll(/^## \[([^\]]+)\]/gm)].map(m=>m[1])).toEqual(FACILITATOR_SECTION_IDS);expect(g).toContain('480');expect(g).toContain('90');expect(g).toContain('not observed');expect(fs.readFileSync('docs/lesson-162-practice-kit.'+l+'.md','utf8').match(/^## /gm)).toHaveLength(5);}});
 it('checks actual successors and every protected baseline byte before exposing predecessors',()=>{execFileSync(process.execPath,['scripts/lesson-162-preservation.mjs']);const receipt=j('docs/lesson-162-proposal-receipt.json');for(const [p,e]of Object.entries(receipt.changed_existing_files)){expect(sha(fs.readFileSync(p))).toBe(e.proposed_sha256);expect(sha(beforeProposed162(p))).toBe(e.predecessor_sha256);}},30000);
 it('selects all eight old Read recordings for old published text after a draft revision',()=>{const read=Object.fromEntries(['fil','en'].map(l=>[l,parseReferenceRead(baseline.target_utf8[leaf+'read.'+l+'.md'])]));const sections=read.fil.map((s,i)=>({id:s.id,heading_fil:s.heading,heading_en:read.en[i].heading,body_fil:s.body,body_en:read.en[i].body,takeaway_fil:old.sections[i].takeaway_fil,takeaway_en:old.sections[i].takeaway_en}));const m=j('content/training/day1-basic-competencies/narration.json');for(const l of ['fil','en']){const selected=narrationForLesson(m,'communication-clarify',l,sections);expect(Object.keys(selected)).toEqual(['open-question','barriers','practice','check']);for(const id of Object.keys(selected))expect(selected[id].src).toBe(baseline.narration.lessons['communication-clarify'].sections[id][l].src);}});
});
