// @vitest-environment node
import {test} from 'vitest';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {loadReferenceModule} from '../lib/reference-content.mjs';import {planReferenceNarration} from '../lib/reference-narration.mjs';
const j=p=>JSON.parse(fs.readFileSync(p));const leaf='content/training/day1-basic-competencies/modules/08-osh/lessons/safety-identify/';
test('Apple adaptation keeps published identities, decision choices and original resume concepts',()=>{const b=j('docs/lesson-181-handoff-baseline.json'),l=j(leaf+'lesson.json'),old=JSON.parse(b.target_files_utf8[leaf+'lesson.json']);assert.deepEqual(l.manifest,b.manifest);for(const s of old.sections){const n=l.sections.find(n=>n.id===s.id);assert(n);assert.deepEqual(n.concept_ids,s.concept_ids);}for(const k of ['options','correct_option_index','prompt_fil','prompt_en'])assert.deepEqual(l.sections.at(-1).check[k],old.sections.at(-1).check[k]);assert.deepEqual(l.sections.map(s=>s.id),['ana','inspect','scope-and-contact','five-hazards','practice','check']);assert(l.sections.every(s=>s.asset_ids.length));assert(l.assets.every(a=>a.review_status==='draft'));});
test('both modes retain complete equivalent text and explicit unknown-contact ending',()=>{const {lessons}=loadReferenceModule('content/training/day1-basic-competencies/modules/08-osh','public');const l=lessons.find(l=>l.manifest.lesson_key==='safety-identify');for(const lang of ['fil','en'])for(const s of l.revision.read_sections){const slide=l.revision.slides.find(x=>x.id==='slide-'+s.id);assert.equal(slide['narration_'+lang],s['body_'+lang]);assert(slide['display_'+lang].length<s['body_'+lang].length);}const check=l.revision.read_sections.at(-1).check;assert.match(check.feedback_en,/do not yet know/);assert.match(check.feedback_fil,/hindi pa natin alam/i);});
test('new target sections use Gemini Kore while previous published selections remain usable by history',()=>{const {lessons}=loadReferenceModule('content/training/day1-basic-competencies/modules/08-osh','public'),n=j('content/training/day1-basic-competencies/narration.json'),hash=p=>fs.existsSync('public'+p)?createHash('sha256').update(fs.readFileSync('public'+p)).digest('hex'):null;const plan=planReferenceNarration([{key:'08-osh',lessons}],n,hash,{provider:'gemini'}).filter(p=>p.lessonKey==='safety-identify');assert.equal(plan.length,12);assert(plan.every(p=>p.voice==='gemini:gemini-3.8-flash-tts:Kore'));const b=j('docs/lesson-181-execution-baseline.json');for(const [key,value]of Object.entries(b.narration.lessons))if(key!=='safety-identify')assert.deepEqual(n.lessons[key],value);});

test('current and original published text select their own exact audio bytes',async()=>{const {parseReferenceRead}=await import('../lib/reference-content.mjs');const {narrationForLesson}=await import('../../src/lib/elearning/reference-narration.ts');const b=j('docs/lesson-181-handoff-baseline.json'),n=j('content/training/day1-basic-competencies/narration.json'),old=JSON.parse(b.target_files_utf8[leaf+'lesson.json']);const {lessons}=loadReferenceModule('content/training/day1-basic-competencies/modules/08-osh','public'),current=lessons.find(l=>l.manifest.lesson_key==='safety-identify');const reads=Object.fromEntries(['fil','en'].map(l=>[l,parseReferenceRead(b.target_files_utf8[leaf+'read.'+l+'.md'])]));const sections=old.sections.map((s,i)=>({...s,heading_fil:reads.fil[i].heading,heading_en:reads.en[i].heading,body_fil:reads.fil[i].body,body_en:reads.en[i].body}));for(const lang of ['fil','en']){const before=narrationForLesson(n,'safety-identify',lang,sections),after=narrationForLesson(n,'safety-identify',lang,current.revision.read_sections);assert.deepEqual(Object.keys(before),['ana','inspect','practice','check']);assert.deepEqual(Object.keys(after),['ana','inspect','scope-and-contact','five-hazards','practice','check']);for(const id of Object.keys(before))assert.equal(before[id].src,b.target_narration.sections[id][lang].src);for(const id of Object.keys(after))assert.notEqual(after[id].src,before[id]?.src);}});
