import {beforeProposed155} from './lesson-155-proposal-compat.mjs';
import {approved153Path,localPartnersLeaf} from './lesson-153-release-compat.mjs';
import {approved154Path,teamworkLeaf} from './lesson-154-release-compat.mjs';
import {beforeApproved156,approved156Path} from './lesson-156-release-compat.mjs';
// @vitest-environment node
import {describe,it,expect} from 'vitest';
import path from 'node:path';import {createHash} from 'node:crypto';
import {loadReferenceModule,parseReferenceRead,FACILITATOR_SECTION_IDS} from '../lib/reference-content.mjs';
import {narrationForLesson} from '../../src/lib/elearning/reference-narration.ts';
import {planReferenceNarration,mp3AudioFrames} from '../lib/reference-narration.mjs';
const root=path.resolve(import.meta.dirname,'../..'),base='content/training/day1-basic-competencies/modules/05-bhw-at-barangay/',leaf=base+'lessons/bhw-right-contact/';
const bytes=p=>read155(root+'/'+p),j=p=>JSON.parse(bytes(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const b=j('docs/lesson-156-current-baseline.json'),s=j(leaf+'lesson.json'),m=j('content/training/day1-basic-competencies/narration.json');
const a=loadReferenceModule(root+'/'+base,root+'/public').lessons.find(x=>x.manifest.lesson_key==='bhw-right-contact');
describe('lesson 1.5.6 complete contact-choice draft',()=>{
 it('preserves immutable identity and substantive original anchors',()=>{expect(s.manifest).toEqual(b.target.manifest);expect(j('content/training/day1-basic-competencies/locks/ltzicxyefizxoqhfuuzc.json')).toEqual(b.uuid_lock);for(const id of ['section-11','section-12']){expect(s.sections.some(x=>x.id===id)).toBe(true);expect(a.revision.read_sections.find(x=>x.id===id).body_en.length).toBeGreaterThan(250);expect(a.revision.slides.some(x=>x.id==='slide-'+id)).toBe(true);}});
 it('has six bilingual narration-equivalent screens with an actual image on every slide',()=>{expect(s.sections).toHaveLength(6);for(const lang of ['fil','en']){const read=parseReferenceRead(bytes(leaf+'read.'+lang+'.md').toString());for(const [i,section]of read.entries()){expect(a.revision.slides[i]['narration_'+lang]).toBe(section.body);expect(section.body).not.toContain('Marites');expect(a.revision.slides[i].asset_ids.length).toBeGreaterThan(0);for(const id of a.revision.slides[i].asset_ids){const art=s.assets.find(x=>x.id===id);expect(sha(bytes('public'+art.path))).toBe(art.content_hash);}}}expect(s.coverage[0].read_ids).toEqual(s.sections.map(x=>x.id));});
 it('explains every choice and retains one complete bilingual indicator and guide outline',()=>{const c=s.sections.at(-1).check;expect(c.options).toHaveLength(3);for(const lang of ['fil','en']){for(const label of lang==='fil'?['Una:','Ikalawa:','Ikatlo:']:['First:','Second:','Third:'])expect(c['feedback_'+lang]).toContain(label);const guide=bytes(leaf+'facilitator.'+lang+'.md').toString();expect([...guide.matchAll(/^## \[([^\]]+)\]/gm)].map(x=>x[1])).toEqual(FACILITATOR_SECTION_IDS);expect(guide).toContain('180');expect(guide).not.toContain('SELF_STUDY_TIMING_PENDING');}const indicators=j(leaf+'competency.json').observation_indicators;expect(indicators).toHaveLength(1);expect(indicators[0].objective_index).toBe(0);expect(Object.keys(indicators[0].levels)).toHaveLength(6);});
 it('preserves every starting public byte, historical receipt and five sibling source sets',()=>{for(const [p,h]of Object.entries(b.tracked_file_hashes)){if(p.startsWith('public/')||/^docs\/lesson-(135|14[1-5]|151|152)-/.test(p)||p.startsWith(base+'lessons/')&&!p.startsWith(leaf)){if(p.startsWith(localPartnersLeaf))approved153Path(p);else if(p.startsWith(teamworkLeaf))approved154Path(p);else expect(sha(bytes(p)),p).toBe(h);}}},30000);
 it('preserves non-target narration and full old target selection with byte-verified history',()=>{for(const [k,v]of Object.entries(b.narration.lessons))if(k==='bhw-local-partners'||k==='bhw-teamwork'){expect(m.history[k]).toContainEqual(v);for(const langs of Object.values(v.sections))for(const track of Object.values(langs))expect(sha(bytes('public'+track.src))).toBe(track.sha256);}else if(k!=='bhw-right-contact')expect(m.lessons[k],k).toEqual(v);for(const [k,v]of Object.entries(b.narration.history??{}))expect(['bhw-right-contact','bhw-local-partners','bhw-teamwork'].includes(k)?m.history[k].slice(0,v.length):m.history[k]).toEqual(v);expect(m.history['bhw-right-contact']).toContainEqual(b.narration.lessons['bhw-right-contact']);const old=j('docs/lesson-156-published-baseline.json').rows.find(x=>x.lesson.lesson_key==='bhw-right-contact').revision;for(const lang of ['fil','en']){const oldTracks=narrationForLesson(m,'bhw-right-contact',lang,old.read_sections);expect(Object.keys(oldTracks)).toEqual(['section-11','section-12']);for(const [id,t]of Object.entries(oldTracks)){expect(t.src).toBe(b.narration.lessons['bhw-right-contact'].sections[id][lang].src);expect(sha(bytes('public'+t.src))).toBe(b.narration.lessons['bhw-right-contact'].sections[id][lang].sha256);}expect(Object.keys(narrationForLesson(m,'bhw-right-contact',lang,a.revision.read_sections))).toEqual(s.sections.map(x=>x.id));}});
 it('selects twelve actual Gemini tracks with measured zones and encoded duration',()=>{const plan=planReferenceNarration([{key:'05-bhw-at-barangay',lessons:[a]}],m,src=>sha(bytes('public'+src)));expect(plan).toHaveLength(12);for(const p of plan){expect(p.action).toBe('skip');expect(p.voice).toBe('gemini:gemini-3.8-flash-tts:Kore');expect(p.existing.timings.map(({zone,index,text})=>({zone,index,text}))).toEqual(p.zones);const seconds=mp3AudioFrames(bytes('public'+p.src)).reduce((sum,f)=>sum+f.samples/f.sampleRate,0);expect(seconds).toBeCloseTo(p.existing.duration_seconds,3);expect(p.existing.timings.at(-1).end_ms).toBeLessThanOrEqual(seconds*1000+1);}});
 it('ships two actual six-cue stories and fourteen full plus focused decoded audio reviews',()=>{const story=s.assets.find(x=>x.id===s.featured_asset_id);expect(story.review_status).toBe('approved');for(const lang of ['fil','en']){const v=story.videos[lang];for(const asset of [v,v.poster,v.captions])expect(sha(bytes('public'+asset.path))).toBe(asset.content_hash);expect(bytes('public'+v.captions.path).toString().match(/ --> /g)).toHaveLength(6);expect(j('remotion/public/bhw-right-contact/narration-'+lang+'.json').beats).toHaveLength(6);}for(const name of ['audio-review','audio-focus']){const report=j('docs/lesson-156-'+name+'.json');expect(report.records).toHaveLength(14);for(const r of report.records){if(name==='audio-review'){expect(r.model_response.length).toBeGreaterThan(100);expect(r.model_response).not.toContain('Review unavailable');}else{expect(r.full_audio_metrics.rms).toBeGreaterThan(0.002);expect(r.excerpts.length).toBeGreaterThanOrEqual(4);}}}});
 it('appends exactly two156compositions while preserving the complete prior registry',()=>{const source=bytes('remotion/src/Root.tsx').toString();expect((source.match(/id=\{language === "fil" \? "BhwRightContactStoryFil"/g)??[])).toHaveLength(1);const prior=source.replace(/^import \{BhwRightContactStory[^\n]+\n/,'').replace(/      \{\(\["fil", "en"\] as const\)\.map\(\(language\) => \(\n        <Composition key=\{`bhw-right-contact-[\s\S]*?      \)\)\}\n/,'');expect(prior).toBe(beforeApproved156('remotion/src/Root.tsx'));approved156Path('remotion/src/Root.tsx');});
 it('limits shared teaching changes to the two final target-owned passages',()=>{for(const lang of ['fil','en']){const p=base+'lesson.'+lang+'.md',now=bytes(p).toString(),old=j('docs/lesson-156-shared-baseline.json')[p];expect(sha(Buffer.from(old))).toBe(b.tracked_file_hashes[p]);const prefix=lang==='en'?'## [practice/standard] Try it:':'## [practice/standard] Subukan mo:';const integrated=beforeApproved156(p);expect(now.slice(0,now.indexOf(prefix))).toBe(integrated.slice(0,integrated.indexOf(prefix)));approved156Path(p);}approved154Path(base+'qa-entries.json');});
});

function read155(p,encoding){const bytes=beforeProposed155(path.relative(root,p));return encoding?bytes.toString(encoding):bytes;}
