// @vitest-environment node
import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {loadReferenceModule,parseReferenceRead,FACILITATOR_SECTION_IDS} from '../lib/reference-content.mjs';
import {planReferenceNarration,mp3AudioFrames} from '../lib/reference-narration.mjs';
import {BHW_FOLLOW_UP_STORY_STYLES} from '../lib/tts-providers/gemini.mjs';
import {BHW_FOLLOW_UP_BEATS} from '../../remotion/src/bhw-follow-up/narration.ts';
import {narrationForLesson} from '../../src/lib/elearning/reference-narration.ts';
import {lessonPosition,continueLesson} from '../../src/lib/elearning/reference-navigation.ts';
import {toWebVtt} from '../lib/webvtt.mjs';
const root=path.resolve(import.meta.dirname,'../..'),base='content/training/day1-basic-competencies/modules/04-ra7883/',dir=root+'/'+base,leaf=dir+'lessons/bhw-follow-up/';
const j=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex'),bytes=src=>fs.readFileSync(root+'/public'+src),hash=src=>sha(bytes(src));
const baseline=j(root+'/docs/lesson-145-start-baseline.json'),source=j(leaf+'lesson.json'),mf=j(root+'/content/training/day1-basic-competencies/narration.json');
const authored=loadReferenceModule(dir,root+'/public').lessons.find(l=>l.manifest.lesson_key==='bhw-follow-up'),modules=[{key:'04-ra7883',lessons:[authored]}];
const ids=['follow-up-question','section-6','known-and-unknown','section-7','next-contact-plan','follow-up-application-check'];
describe('lesson1.4.5 constructive follow-up approved release',()=>{
 it('preserves identity/single objective and full bilingual Read/Slide parity',()=>{expect(source.manifest).toEqual(baseline.immutable_manifest);expect(source.sections.map(s=>s.id)).toEqual(ids);for(const lang of ['fil','en']){const read=parseReferenceRead(fs.readFileSync(leaf+`read.${lang}.md`,'utf8'));expect(read.map(s=>s.id)).toEqual(ids);for(const [i,s]of read.entries()){expect(authored.revision.slides[i].id).toBe('slide-'+s.id);expect(authored.revision.slides[i][`narration_${lang}`]).toBe(s.body);}}expect(source.coverage).toHaveLength(1);expect(source.coverage[0]).toMatchObject({id:'m4.competency',read_ids:ids,slide_ids:ids.map(id=>'slide-'+id)});for(const id of source.coverage[0].source_ids)expect(source.sources.some(s=>s.id===id)).toBe(true);});
 it('keeps both substantive old resume IDs and completion independent of optional story',()=>{const lesson={...authored.manifest,id:'1a2029ac-c29c-471f-b492-9307be567959',revision:{...authored.revision,id:'new-draft'}};for(const mode of ['read','slides'])for(const old of ['section-6','section-7']){const id=mode==='read'?old:'slide-'+old;expect(lessonPosition(lesson,mode,{lesson_id:lesson.id,revision_id:'old-published',position_key:id,concept_id:'m4.competency',modality:mode}).id).toBe(id);}expect(continueLesson([lesson],[{lesson_id:lesson.id}],[])).toBeNull();expect(authored.revision.read_sections[0].body_en).toContain('optional');});
 it('teaches bounded factual inquiry and explains all three application choices',()=>{const text=authored.revision.read_sections.map(s=>s.body_en).join(' ');expect(text).not.toMatch(/Josie|every two months|six months|You now know the whole process|silence isn.t politeness/);expect(text).toContain('She does not know the cause');expect(text).toContain('respectful and firm');expect(text).toContain('does not guarantee');expect(text).toContain('Card A');expect(text).toContain('Card B');expect(text).toContain('Card C');const check=source.sections.at(-1).check;expect(check.options).toHaveLength(3);expect(check).toEqual(authored.revision.slides.at(-1).check);expect(check.correct_option_index).toBe(0);expect(check.feedback_en).toMatch(/First:.*Second:.*Third:/);expect(check.feedback_fil).toMatch(/Una:.*Ikalawa:.*Ikatlo:/);});
 it('plans only target Kore/style with exact text/style/byte cache invalidation',()=>{for(const options of [{},{provider:'gemini'}]){const plan=planReferenceNarration(modules,mf,hash,options);expect(plan).toHaveLength(12);for(const item of plan){expect(item.provider).toBe('gemini');expect(item.voice).toBe('gemini:gemini-3.8-flash-tts:Kore');expect(item.speechStyle).toBe(BHW_FOLLOW_UP_STORY_STYLES[item.language]);expect(item.action).toBe('skip');}}const changed=structuredClone(modules);changed[0].lessons[0].revision.read_sections[0].body_en+=' Clarify.';expect(planReferenceNarration(changed,mf,hash).find(i=>i.sectionId===ids[0]&&i.language==='en').action).toBe('render');const style=BHW_FOLLOW_UP_STORY_STYLES.en;try{BHW_FOLLOW_UP_STORY_STYLES.en+=' Pause.';expect(planReferenceNarration(modules,mf,hash).find(i=>i.language==='en').action).toBe('render');}finally{BHW_FOLLOW_UP_STORY_STYLES.en=style;}expect(planReferenceNarration(modules,mf,()=> 'bad').every(i=>i.action==='render')).toBe(true);});
 it('has twelve real tracks with exact text zones and finite measured durations',()=>{for(const item of planReferenceNarration(modules,mf,hash)){expect(item.action).toBe('skip');const t=item.existing;expect(t.timings.map(({zone,index,text})=>({zone,index,text}))).toEqual(item.zones);const duration=mp3AudioFrames(bytes(item.src)).reduce((sum,f)=>sum+f.samples/f.sampleRate,0);expect(t.duration_seconds).toBeCloseTo(duration,3);for(const [i,z]of t.timings.entries()){expect(Number.isFinite(z.start_ms)).toBe(true);expect(z.end_ms).toBeGreaterThan(z.start_ms);if(i)expect(z.start_ms).toBeGreaterThanOrEqual(t.timings[i-1].end_ms);}expect(t.timings.at(-1).end_ms).toBeLessThanOrEqual(duration*1000+1);}});
 it('selects four actual published tracks and twelve new tracks using unchanged production selector',()=>{const published=baseline.published_rows.find(r=>r.lesson_key==='bhw-follow-up');expect(mf.history['bhw-follow-up']).toContainEqual(baseline.original_target_mapping);for(const lang of ['fil','en']){const old=narrationForLesson(mf,'bhw-follow-up',lang,published.read_sections);expect(Object.keys(old)).toEqual(['section-6','section-7']);for(const id of Object.keys(old))expect(old[id].src).toBe(baseline.original_target_mapping.sections[id][lang].src);expect(Object.keys(narrationForLesson(mf,'bhw-follow-up',lang,authored.revision.read_sections))).toEqual(ids);}});
 it('protects every starting MP3, non-target mapping/history and approved sibling media',()=>{for(const [p,h]of Object.entries(baseline.original_audio_hashes))expect(sha(fs.readFileSync(root+'/'+p))).toBe(h);for(const [k,v]of Object.entries(baseline.non_target_mappings)){if(k==='bhw-relationships'||k==='bhw-barangay-partners'||k==='bhw-right-contact'){expect(mf.history[k]).toContainEqual(v);for(const langs of Object.values(v.sections))for(const track of Object.values(langs))expect(hash(track.src)).toBe(track.sha256);}else expect(mf.lessons[k]).toEqual(v);}for(const [k,v]of Object.entries(baseline.original_history)){if(k==='bhw-barangay-partners'||k==='bhw-right-contact')expect(mf.history[k].slice(0,v.length)).toEqual(v);else expect(mf.history[k]).toEqual(v);}for(const m of baseline.protected_media)expect(hash(m.path)).toBe(m.sha256);},30000);
 it('protects all sibling working/Git bytes and target immutable UUID lock',()=>{for(const [p,h]of Object.entries(baseline.sibling_files)){expect(sha(fs.readFileSync(root+'/'+p))).toBe(process.platform==='win32'?h.working_sha256:h.git_sha256);expect(sha(execFileSync('git',['show','HEAD:'+p],{cwd:root}))).toBe(h.git_sha256);}const lock=fs.readFileSync(root+'/content/training/day1-basic-competencies/locks/ltzicxyefizxoqhfuuzc.json','utf8');expect(lock).toContain('1a2029ac-c29c-471f-b492-9307be567959');});
 it('uses genuinely new art with supplied Demi input and exact animation/public bytes',()=>{const art=source.assets.find(a=>a.id==='demi-follow-up'),p=j(root+'/docs/lesson-145-art-provenance.json');expect(hash(art.path)).toBe(art.content_hash);expect(sha(fs.readFileSync(root+'/remotion/public/bhw-follow-up/scene.png'))).toBe(art.content_hash);expect(p.output_sha256).toBe(art.content_hash);expect(p.reference_sha256).toBe('032a985f9c336b745a99d284e2143d7559f070f76f6e85e64dbdaf4c7f9a89b2');expect(p.output_sha256).not.toBe(p.reference_sha256);expect(p.model_id).toBeNull();expect(art.review_status).toBe('approved');});
 it('ships two measured captioned six-beat stories and complete ending',()=>{const asset=source.assets.find(a=>a.id===source.featured_asset_id);expect(asset.review_status).toBe('approved');for(const lang of ['fil','en']){const v=asset.videos[lang],t=j(root+`/remotion/public/bhw-follow-up/narration-${lang}.json`);for(const m of [v,v.poster,v.captions])expect(hash(m.path)).toBe(m.content_hash);expect(t.beats.map(b=>b.zone)).toEqual(BHW_FOLLOW_UP_BEATS.map(b=>b.id));expect(t.beats.map(b=>b.text)).toEqual(BHW_FOLLOW_UP_BEATS.map(b=>b[lang]));expect(bytes(v.captions.path).toString().replaceAll('\r','')).toBe(toWebVtt(t));expect(v.duration_s).toBeLessThanOrEqual(90);expect(v.duration_s).toBeGreaterThan(t.durationSeconds);expect(sha(fs.readFileSync(root+`/remotion/public/bhw-follow-up/narration-${lang}.mp3`))).toBe(t.audio_sha256);}});
 it('retains ordered composition registry and adds exactly two target IDs',()=>{const registry=fs.readFileSync(root+'/remotion/src/Root.tsx','utf8').replaceAll('\r\n','\n').replace(/^import \{BhwRightContactStory[^\n]+\n/,'').replace(/      \{\(\["fil", "en"\] as const\)\.map\(\(language\) => \(\n        <Composition key=\{`bhw-right-contact-[\s\S]*?      \)\)\}\n/,'').replace(/^import \{BhwBarangayPartnersStory[^\n]+\n/,'').replace(/      \{\(\["fil", "en"\] as const\)\.map\(\(language\) => \(\n        <Composition key=\{`bhw-barangay-partners-[\s\S]*?      \)\)\}\n/,'').replace(/^import \{BhwRelationshipsStory[^\n]+\n/,'').replace(/      \{\(\["fil", "en"\] as const\)\.map\(\(language\) => \(\n        <Composition key=\{`bhw-relationships-[\s\S]*?      \)\)\}\n/,'');const original=registry.replace(/^import \{BhwFollowUpStory[^\n]+\n/,'').replace(/      \{\(\["fil", "en"\] as const\)\.map\(\(language\) => \(\n        <Composition key=\{`bhw-follow-up-[\s\S]*?      \)\)\}\n/,'');expect(original.replaceAll('\r\n','\n')).toBe(baseline.composition_registry.replaceAll('\r\n','\n'));});
 it('has twelve guide headings, one indicator and module-indexed optional30min activity',()=>{for(const lang of ['fil','en']){const notes=fs.readFileSync(leaf+`facilitator.${lang}.md`,'utf8');expect([...notes.matchAll(/^## \[([^\]]+)\]/gm)].map(m=>m[1])).toEqual(FACILITATOR_SECTION_IDS);for(const value of ['45','30','180','Card A','Card B','Card C'])expect(notes).toContain(value);}const indicators=j(leaf+'competency.json').observation_indicators;expect(indicators).toHaveLength(1);expect(indicators[0].objective_index).toBe(0);expect(Object.keys(indicators[0].levels)).toHaveLength(6);const a=j(dir+'activities.json').find(x=>x.id==='form-and-follow-up');expect(a).toMatchObject({version:2,minutes:30,optional:true,objective_indices:[3],lesson_keys:['bhw-follow-up']});expect(a.observe[0].en).toContain('indicator4');});
 it('confines shared changes to exact target rows and guide passages',()=>{const qa=j(dir+'qa-entries.json').entries,oldQa=JSON.parse(baseline.shared_files[base+'qa-entries.json']).entries;expect(qa.map(q=>q.id)).toEqual(oldQa.map(q=>q.id));for(const row of qa)if(row.id!=='d1m4-follow-up')expect(row).toEqual(oldQa.find(q=>q.id===row.id));expect(qa.find(q=>q.id==='d1m4-follow-up').sources).toEqual(['bhw-follow-up-training']);const activities=j(dir+'activities.json'),oldA=JSON.parse(baseline.shared_files[base+'activities.json']);expect(activities.map(a=>a.id)).toEqual(oldA.map(a=>a.id));for(const a of activities)if(a.id!=='form-and-follow-up')expect(a).toEqual(oldA.find(x=>x.id===a.id));const mask=t=>t.replaceAll('\r\n','\n').replace('original PDF 25 / printed 16','original PDF 23 / printed 16').replace(/^6\. [\s\S]*?(?=^## )/m,'').replace(/^- "(?:Have you ever waited a long time on a process with no follow-up\?\n  What happened\?|May pagkakataon na ba kayong naghintay nang matagal sa isang\n  proseso nang walang follow-up\? Ano ang nangyari\?|In Demi’s fictional case, what is known, what is unknown and what next-contact question fits\?|Sa fictional case ni Demi, ano ang alam, ano ang unknown at anong next-contact question ang angkop\?)"$/m,'').split('\n4. **')[0];for(const lang of ['fil','en'])expect(mask(fs.readFileSync(dir+`facilitator-notes.${lang}.md`,'utf8')).trimEnd()).toBe(mask(baseline.shared_files[base+`facilitator-notes.${lang}.md`]).trimEnd());});
});

describe('lesson 1.4.5 owner approval',()=>{it('binds the exact reviewed source, packages and all 19 shipped media',()=>{const a=j(root+'/docs/lesson-145-owner-approval.json');expect(a.authorization).toBe('approved. merge and deploy to live');expect(a.reviewed_head).toBe('c40d584977ceb17d19c4d75e1042e474ba0df159');expect(a.reviewed_package_hashes).toEqual({"lesson-1.4.5-demi-review.html":"fb469abeb37a26c432f437f8bcc01c59c64db39ab6a18eaa9ad32deb12a0e30b","lesson-1.4.5-demi-review.zip":"9af3a8771707aaa28080c300a3579c44591bd2333e3cd732824c0d9df4a47a3e"});expect(a.approved_asset_ids).toEqual(['demi-follow-up','bhw-follow-up-story']);expect(a.approved_media).toHaveLength(19);for(const m of a.approved_media)expect(hash(m.path)).toBe(m.sha256);expect(source.assets.every(x=>x.review_status==='approved')).toBe(true);});});
