#!/usr/bin/env python3
"""Freeze a portable, self-contained lesson 1.5.3 owner review package from actual generated bytes."""
import base64,hashlib,html,json,mimetypes,pathlib,zipfile,re,sys
ROOT=pathlib.Path(__file__).resolve().parent.parent
LEAF=ROOT/'content/training/day1-basic-competencies/modules/05-bhw-at-barangay/lessons/bhw-local-partners'
OUT=ROOT/'.preview/lesson-153';OUT.mkdir(parents=True,exist_ok=True)
def sha(b):return hashlib.sha256(b).hexdigest()
def raw(rel):return (ROOT/rel).read_bytes()
def j(rel):return json.loads(raw(rel))
lesson=j(LEAF.relative_to(ROOT)/'lesson.json')
slides=j(LEAF.relative_to(ROOT)/'slides.json')
manifest=j('content/training/day1-basic-competencies/narration.json')
review=j('docs/lesson-153-audio-review.json');focused=j('docs/lesson-153-audio-focus.json')
assert len(slides)==6 and len(review['records'])==len(focused['records'])==14
assert set(s['id'] for s in slides)==set('slide-'+s['id'] for s in lesson['sections'])
assert all(len(s['asset_ids'])>=2 for s in slides)
media={}; selected=[]
def add(path,expected=None):
 rel=path.lstrip('/');data=raw('public/'+rel)
 if expected:assert sha(data)==expected,(path,'content hash mismatch')
 media[path]={'sha256':sha(data),'data':base64.b64encode(data).decode(),'mime':mimetypes.guess_type(path)[0] or 'application/octet-stream','size':len(data)}
 selected.append('public/'+rel)
for a in lesson['assets']:
 if 'path' in a:add(a['path'],a['content_hash'])
 for v in a.get('videos',{}).values():
  for m in (v,v['poster'],v['captions']):add(m['path'],m['content_hash'])
for lang in ('fil','en'):
 for s in lesson['sections']:
  track=manifest['lessons']['bhw-local-partners']['sections'][s['id']][lang]
  assert track['voice']=='gemini:gemini-3.8-flash-tts:Kore'
  add(track['src'],track['sha256'])
assert len([p for p in selected if p.endswith('.mp3')])==12
assert len([p for p in selected if p.endswith('.mp4')])==2
# All public media are inlined, including six slide cues.
ui={'lesson':lesson,'slides':slides,'manifest':manifest['lessons']['bhw-local-partners'],'media':media,
    'guides':{l:raw(LEAF.relative_to(ROOT)/f'facilitator.{l}.md').decode() for l in ('fil','en')},
    'indicator':j(LEAF.relative_to(ROOT)/'competency.json'),
    'source_audit':j('docs/lesson-153-source-audit.json'),
    'audio_review':review,'audio_focus':focused}
payload=json.dumps(ui,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 1.5.3 — Malou review</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#183a37;background:#eef4f0}*{box-sizing:border-box}body{margin:0}header{background:#174e49;color:white;padding:18px max(16px,calc((100vw - 1120px)/2))}h1{font-size:1.4rem;margin:.3rem 0}main{max-width:1120px;margin:auto;padding:18px;display:grid;gap:16px}button,select{font:inherit;min-height:42px;padding:8px 12px;border:1px solid #779c93;border-radius:10px;background:white;color:#163e39;cursor:pointer}button[aria-current=true]{background:#174e49;color:white}nav{display:flex;flex-wrap:wrap;gap:8px}.card{background:white;border-radius:18px;padding:18px;box-shadow:0 4px 16px #173e3920;min-width:0}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.55fr);gap:16px}.figures{display:grid;gap:12px;align-content:start}figure{margin:0}figure img{width:100%;height:auto;max-height:280px;object-fit:contain;border-radius:12px;background:#edf4f0}figcaption{font-size:.85rem;color:#365d58}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;line-height:1.55}p{line-height:1.55}audio,video{width:100%;margin-top:12px}video{max-height:440px;background:#142c2b}.choice{display:block;width:100%;text-align:left;margin:8px 0}.feedback{border-left:4px solid #b57b2f;padding:12px;background:#fff7e9}.proof{font-family:ui-monospace,monospace;font-size:.82rem;max-height:360px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}.status{font-size:.9rem;color:#bdddd3}@media(max-width:740px){.layout{grid-template-columns:1fr}header{padding:16px}main{padding:12px}.card{padding:14px}nav button{flex:1 1 100px}}
</style></head><body><header><h1>Lesson 1.5.3 · Malou</h1><div class="status">Draft bilingual review · local media only · owner approval pending</div></header><main><nav id="controls"></nav><div id="app"></div></main><script id="payload" type="application/json">__DATA__</script><script>
const D=JSON.parse(document.getElementById('payload').textContent);let lang='fil',mode='slides',index=0,choice=-1;const $=id=>document.getElementById(id);const txt=(o,key)=>o[key+'_'+lang];const uri=p=>'data:'+D.media[p].mime+';base64,'+D.media[p].data;const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function controls(){const c=$('controls');c.innerHTML=['fil','en'].map(l=>`<button data-lang="${l}" aria-current="${lang===l}">${l==='fil'?'Filipino':'English'}</button>`).join('')+['slides','read','story','guide','proof'].map(m=>`<button data-mode="${m}" aria-current="${mode===m}">${m.toUpperCase()}</button>`).join('');c.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;choice=-1;render()});c.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;choice=-1;render()})}
function current(){const s=D.lesson.sections[index],slide=D.slides[index],isSlide=mode==='slides',v=isSlide?slide:s;const body=isSlide?txt(slide,'display'):txt(s,'body');const track=D.manifest.sections[s.id][lang];const figures=v.asset_ids.map(id=>{const a=D.lesson.assets.find(x=>x.id===id);return `<figure><img src="${uri(a.path)}" alt="${esc(txt(a,'alt'))}"><figcaption>${esc(txt(a,'caption'))}</figcaption></figure>`}).join('');let check='';if(v.check){check=`<h3>${esc(txt(v.check,'prompt'))}</h3>`+v.check.options.map((o,i)=>`<button class="choice" data-choice="${i}">${esc(o[lang])}</button>`).join('')+(choice<0?'':`<p class="feedback">${esc(txt(v.check,'feedback'))}</p>`)}
 $('app').innerHTML=`<div class="card"><nav><button id="prev" ${index===0?'disabled':''}>←</button><strong>${index+1} / 6 · ${esc(txt(v,'heading'))}</strong><button id="next" ${index===5?'disabled':''}>→</button></nav></div><div class="layout"><section class="card"><h2>${esc(txt(v,'heading'))}</h2><pre>${esc(body)}</pre>${isSlide?'':`<p><strong>${esc(txt(s,'takeaway'))}</strong></p>`}<audio controls preload="none" src="${uri(track.src)}"></audio>${check}</section><aside class="card figures">${figures}</aside></div>`;
 $('prev').onclick=()=>{index--;choice=-1;render()};$('next').onclick=()=>{index++;choice=-1;render()};document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choice=Number(b.dataset.choice);render()});}
function render(){controls();if(mode==='slides'||mode==='read'){current();return}if(mode==='story'){const a=D.lesson.assets.find(x=>x.id==='bhw-local-partners-story');const v=a.videos[lang];$('app').innerHTML=`<section class="card"><h2>${esc(txt(a,'caption'))}</h2><video controls playsinline poster="${uri(v.poster.path)}"><source src="${uri(v.path)}" type="video/mp4"><track default kind="captions" srclang="${lang==='fil'?'fil':'en'}" src="${uri(v.captions.path)}"></video><p>${esc(txt(a,'alt'))}</p></section>`;return}if(mode==='guide'){$('app').innerHTML=`<section class="card"><h2>Facilitator guide</h2><pre>${esc(D.guides[lang])}</pre><h2>Observable indicator</h2><pre>${esc(JSON.stringify(D.indicator,null,2))}</pre></section>`;return}$('app').innerHTML=`<section class="card"><h2>Evidence and limits</h2><pre class="proof">${esc(JSON.stringify({source_audit:D.source_audit,media_sha256:Object.fromEntries(Object.entries(D.media).map(([k,v])=>[k,v.sha256])),audio_review:D.audio_review,audio_focus:D.audio_focus},null,2))}</pre></section>`}render();</script></body></html>'''.replace('__DATA__',payload)
html_path=OUT/'lesson-1.5.3-malou-review.html';html_path.write_text(page)
files={'lesson-1.5.3-malou-review.html':html_path.read_bytes()}
for rel in sorted(set(selected)):files[rel]=raw(rel)
for p in [*sorted(LEAF.glob('*')),ROOT/'docs/lesson-153-source-audit.json',ROOT/'docs/lesson-153-media-generation.json',ROOT/'docs/lesson-153-audio-review.json',ROOT/'docs/lesson-153-audio-focus.json',ROOT/'content/training/day1-basic-competencies/narration.json']:
 if p.is_file():files['source/'+str(p.relative_to(ROOT))]=p.read_bytes()
index={'lesson':'1.5.3','status':'draft pending owner review','member_sha256':{k:sha(v) for k,v in files.items()},'media_sha256':{k:v['sha256'] for k,v in media.items()},'original_source_pdf_status':'unavailable in this workspace; inherited receipts retained without claiming new PDF audit'}
files['integrity.json']=json.dumps(index,indent=2).encode()
zip_path=OUT/'lesson-1.5.3-malou-review.zip'
with zipfile.ZipFile(zip_path,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=7) as z:
 for name,bytes_ in files.items():
  assert not pathlib.PurePosixPath(name).is_absolute() and '..' not in pathlib.PurePosixPath(name).parts
  z.writestr(name,bytes_)
with zipfile.ZipFile(zip_path) as z:
 assert z.testzip() is None and len(z.namelist())==len(set(z.namelist()))
 for name,b in files.items():assert z.read(name)==b
(OUT/'lesson-1.5.3-package-integrity.json').write_text(json.dumps({**index,'html_sha256':sha(html_path.read_bytes()),'zip_sha256':sha(zip_path.read_bytes()),'zip_bytes':zip_path.stat().st_size},indent=2)+'\n')
print(html_path,zip_path,len(files),'members')
