"""Import actual target media only from a hash-pinned CI artifact, with safe ZIP paths."""
import pathlib,json,hashlib,zipfile,sys
r=pathlib.Path(__file__).resolve().parent.parent;archive=pathlib.Path(sys.argv[1]);sha=lambda b:hashlib.sha256(b).hexdigest();run=sys.argv[2]
allowed_prefixes=['public/training/audio/08-osh/safety-controls/','.preview/lesson182-raw/','.preview/lesson182-excerpts/','remotion/public/safety-controls/shipped-aac-','remotion/public/safety-controls/narration-','public/training/bhw-1-8/safety-controls-']
allowed_names=['content/training/day1-basic-competencies/narration.json','docs/lesson-182-media-generation.json','docs/lesson-182-audio-review.json','docs/lesson-182-audio-focus.json','lesson-182-published-snapshot.json',*['content/training/day1-basic-competencies/modules/08-osh/lessons/safety-controls/'+n for n in ['lesson.json','facilitator.fil.md','facilitator.en.md']]]
records=[]
with zipfile.ZipFile(archive) as z:
 names=z.namelist();assert len(names)==len(set(names));assert z.testzip() is None
 for info in z.infolist():
  p=pathlib.PurePosixPath(info.filename);assert not p.is_absolute() and '..' not in p.parts and '\\' not in info.filename
  if info.is_dir():continue
  data=z.read(info);records.append({'path':info.filename,'bytes':len(data),'sha256':sha(data)})
  if not(info.filename in allowed_names or any(info.filename.startswith(prefix) for prefix in allowed_prefixes)):continue
  target=r/info.filename
  if info.filename.startswith('public/') and target.exists():assert target.read_bytes()==data,'Immutable media conflict '+info.filename
  target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
receipt={'status':'imported actual CI-generated bytes; no owner approval','run_id':run,'run_url':'https://github.com/jongsky25/BHW-Connect-Phase-2/actions/runs/'+run,'archive_sha256':sha(archive.read_bytes()),'archive_bytes':archive.stat().st_size,'safe_unique_paths_and_crc':True,'members':records}
(r/('docs/lesson-182-final-evidence-origins.json' if len(sys.argv)>3 and sys.argv[3]=='final' else 'docs/lesson-182-story-evidence-origins.json' if len(sys.argv)>3 and sys.argv[3]=='story' else 'docs/lesson-182-evidence-origins.json')).write_text(json.dumps(receipt,indent=2)+'\n');print('Imported allowed target files from',len(records),'verified members')
