// Review-only content. This is not an input to the production training loader.
const b = (fil, en) => ({fil, en});
const section = (id, concepts, title, read, layout, asset, labels, caption) => ({
  id, concepts: concepts.split(' '), title, read,
  slide: {id: `${id}-slide`, layout, asset, labels, caption},
});
const check = (prompt, options, correct, feedback) => ({prompt, options, correct, feedback});
export const course = {
  id: 'bhw-reference-manual', title: 'BHW Reference Manual Training', revision: 'prototype-1',
  legacyCourse: 'day1-basic-competencies', legacyModule: '01-tungkulin-ng-bhw', proposedLessonCount: 42,
  chapters: [
    b('Ang BHWs at ang Kanilang Barangay', 'BHWs and Their Barangay'),
    b('Ang BHWs bilang First Responder', 'BHWs as First Responders'),
    b('Ang BHW bilang Tagapagsulong ng Primary Care', 'The BHW as a Primary Care Advocate'),
  ],
  subchapters: [
    b('Ang mga Tungkulin ng BHW','The Roles of a BHW'), b('Ang UHC Act','The UHC Act'),
    b('Mga Polisiya sa BHS','BHS Policies'), b('Mga Karapatan at Benepisyo ng BHW','BHW Rights and Benefits'),
    b('Ang BHW at ang Kanyang Barangay','The BHW and Their Barangay'), b('Epektibong Pakikipagkomunikasyon','Effective Communication'),
    b('Pagkilala sa Problema at Pagpaplano ng Solusyon','Identifying Problems and Planning Solutions'),
    b('Occupational Safety and Health','Occupational Safety and Health'), b('Napapanatiling mga Gawi sa Trabaho','Sustainable Workplace Practices'),
  ],
};
export const lessons = [
  {
    id:'bhw-roles-hepo', number:'1.1.1', title:b('Ang BHW at ang HEPO','The BHW and HEPO'), minutes:'3–5',
    objective:b('Maipaliwanag kung paano nagsasama ang pagtuturo, pag-oorganisa, at pagtulong sa serbisyo sa papel ng BHW.','Explain how education, organizing, and service support work together in the BHW role.'),
    sources:'Reference Manual PDF 11–12; Facilitator Guide PDF 19–20; Day 1 presentation PDF 5–8, 13.',
    sections:[
      section('morning','m1.uhc.shift',b('Isang umaga, maraming gawain','One morning, many tasks'),
        b('Alas-otso, may talakayang pangkalusugan si BHW Marites sa purok. Alas-diyes, kausap niya ang kagawad tungkol sa clean-up drive. Alas-onse, tinutulungan niya si Aling Nena na makausap ang midwife tungkol sa pangangailangan ng anak nito. Iisang BHW ang gumagawa ng tatlo. Sa curriculum, ang direksyon ng UHC ay mas matibay na primary care at health promotion; kaya mas malawak ang papel kaysa pagtulong sa serbisyo lamang.',
          'At eight, BHW Marites leads a health discussion in the purok. At ten, she talks with the council member about a clean-up drive. At eleven, she helps Aling Nena contact the midwife about her child’s needs. One BHW does all three. The curriculum describes UHC as strengthening primary care and health promotion, so the role extends beyond service support.'),
        'scene','A01',[b('08:00 · Magturo','08:00 · Educate'),b('10:00 · Mag-organisa','10:00 · Organize'),b('11:00 · Gumabay','11:00 · Guide')],
        b('Primary care + health promotion: higit sa pagtulong sa serbisyo.','Primary care + health promotion: a role beyond service support.')),
      section('prevention','m1.uhc.organizing',b('Kumilos kasama ang komunidad','Act with the community'),
        b('Mahalaga ang serbisyo kapag kailangan ito. Kasabay nito, nagtuturo ang BHW at hinihikayat ang mga tao na makilahok sa mga gawaing pangkalusugan. Sa clean-up drive ni Marites, may kaalamang ibinabahagi at may mga residenteng kasamang nagpaplano at kumikilos. Magkaugnay ang edukasyon, pakikilahok, at paglapit sa serbisyo.',
          'Services matter when people need them. Alongside this, the BHW teaches and encourages people to join health activities. In Marites’s clean-up drive, information is shared and residents help plan and act. Education, participation, and access to services are connected.'),
        'process','A04',[b('Magbahagi ng kaalaman','Share knowledge'),b('Mag-anyaya ng pakikilahok','Invite participation'),b('Magkatuwang na kumilos','Act together')],
        b('Kasama ang pagtuturo at pag-oorganisa sa pagsulong ng kalusugan.','Education and organizing contribute to health promotion.')),
      section('hepo','m1.hepo.umbrella',b('HEPO: pagsusulong ng kalusugan','HEPO: promoting health'),
        b('Ginagamit ng Reference Manual ang katawagang barangay-level Health Education and Promotion Officer o HEPO. Inilalarawan nito ang papel ng BHW sa pagbabahagi ng impormasyong pangkalusugan. Makikita ang papel na ito sa pagiging Health Educator, Community Organizer, at Health Service Provider. Ang ugnayan sa larawan ay paliwanag ng magkakaugnay na gawain; hindi ito opisyal na organizational chart o patunay ng appointment.',
          'The Reference Manual uses the term barangay-level Health Education and Promotion Officer, or HEPO. It describes the BHW’s role in sharing health information. This role is expressed through being a Health Educator, Community Organizer, and Health Service Provider. The visual connects related tasks; it is not an official organizational chart or proof of an appointment.'),
        'roles','A02',[b('Health Educator','Health Educator'),b('Community Organizer','Community Organizer'),b('Health Service Provider','Health Service Provider')],
        b('HEPO = Health Education and Promotion Officer. Magkakaugnay na gawain, hindi reporting hierarchy.','HEPO = Health Education and Promotion Officer. Connected tasks, not a reporting hierarchy.')),
      section('knowledge','m1.hepo.knowledge',b('Bago magbahagi, maghanda','Prepare before sharing'),
        b('Kailangan ni Marites ng sapat na kaalaman sa mga prayoridad na programa at problemang pangkalusugan sa barangay. Bago magturo, sinisiguro niyang malinaw sa kanya ang impormasyong ibabahagi. Kapag may detalyeng hindi tiyak, kinukumpirma niya ito sa kaukulang health worker at ginagamit ang aprubadong materyal. Hindi kailangang hulaan ang sagot para makatulong.',
          'Marites needs adequate knowledge of the barangay’s priority health programs and problems. Before teaching, she makes sure she understands the information. When a detail is uncertain, she confirms it with the appropriate health worker and uses approved materials. Helping does not require guessing an answer.'),
        'process','A02',[b('Mga prayoridad na programa','Priority programs'),b('Mga problemang pangkalusugan','Health problems'),b('Tamang impormasyong ibabahagi','Accurate information to share')],
        b('Sapat na kaalaman ang pundasyon ng tatlong tungkulin.','Adequate knowledge supports all three roles.')),
    ],
    check:check(b('Nakipagplano si Marites sa mga residente para sa clean-up drive. Aling papel ang pinakakitang-kita?','Marites plans a clean-up drive with residents. Which role is most visible?'),
      [b('Health Service Provider','Health Service Provider'),b('Community Organizer','Community Organizer'),b('Health Educator lamang','Health Educator only')],1,
      b('Community Organizer: nag-uugnay siya ng mga tao at humihikayat ng pagkilos. Maaari ring may pagtuturo sa parehong gawain; hindi eksklusibo ang mga papel.','Community Organizer: she connects people and encourages action. Education can also occur in the same activity; the roles are not exclusive.')),
    takeaway:b('Isang BHW, tatlong magkakaugnay na papel, iisang layuning isulong ang kalusugan.','One BHW, three connected roles, one aim: promoting health.'),
  },
  {
    id:'bhw-health-educator',number:'1.1.2',title:b('Bilang Health Educator','As a Health Educator'),minutes:'3–5',
    objective:b('Matukoy ang angkop na gawaing pang-edukasyon para sa iba’t ibang sektor at yugto ng buhay.','Identify education suited to different community groups and life stages.'),
    sources:'Reference Manual PDF 11–12; Facilitator Guide PDF 20; Day 1 presentation PDF 9.',
    sections:[
      section('educator-scene','m1.role.educator',b('Magsimula sa kausap','Start with your audience'),
        b('Sa talakayan ni Marites, hindi sapat na basahin lang ang poster. Inaalam niya muna kung ano ang tanong ng mga residente, saka nagbibigay ng malinaw na paliwanag. Bilang Health Educator, tinutulungan niyang magkaroon ng kaalaman ang mga tao para mapangalagaan ang kanilang katawan at kapaligiran.',
          'During her discussion, Marites does more than read a poster. She first learns what residents are asking, then explains clearly. As a Health Educator, she helps people gain knowledge to care for their bodies and their environment.'),
        'scene','A01',[b('Makinig sa tanong','Listen to the question'),b('Ipaliwanag nang malinaw','Explain clearly')],b('Ang pagtuturo ay pag-uusap na may layunin.','Teaching is a purposeful conversation.')),
      section('body-environment','m1.role.educator',b('Katawan at kapaligiran','Body and environment'),
        b('Kasama sa edukasyong pangkalusugan ang katawan at ang kapaligiran nito. Maaaring pag-usapan ang paglapit sa serbisyong pangkalusugan at ang kalinisan ng paligid, gamit ang materyal na aprubado ng health team. Ang araling ito ay tungkol sa pagpili ng paksa at kausap; ang detalyadong payong pangkalusugan ay nasa kaukulang pagsasanay.',
          'Health education includes the body and its environment. A discussion may address access to health services and cleanliness of the surroundings, using materials approved by the health team. This lesson concerns choosing a topic and audience; detailed health advice belongs in the relevant training.'),
        'comparison','A03',[b('Katawan · pangangalaga sa sarili','Body · personal health'),b('Kapaligiran · malinis na paligid','Environment · clean surroundings')],b('Magkaugnay ang kalusugan ng tao at ng kanyang paligid.','People’s health and their surroundings are connected.')),
      section('life-stages','m1.educator.lifestages',b('Iba ang pangangailangan sa bawat yugto','Needs change through life'),
        b('Patuloy ang pagtuturo sa bawat yugto ng buhay. Iba ang mga tanong ng tagapag-alaga ng sanggol, kabataan, buntis, at nakatatanda. Kailangang iangkop ang usapan tungkol sa mga sakit, aksidente, at panganib na kaugnay ng kanilang yugto. Halimbawa, iba ang konteksto ng pag-uusap sa kabataan kaysa sa tagapag-alaga ng sanggol.',
          'Education continues through every life stage. An infant’s caregiver, a young person, a pregnant resident, and an older adult have different questions. Discussions of illness, accidents, and risks must fit their life stage. For example, a conversation with a young person has a different context from one with an infant’s caregiver.'),
        'audience','A03',[b('Sanggol at tagapag-alaga','Infant and caregiver'),b('Kabataan','Young people'),b('Buntis','Pregnant residents'),b('Nakatatanda','Older adults')],b('Iangkop ang usapan tungkol sa sakit, aksidente, at panganib sa yugto ng buhay.','Adapt discussion of illness, accidents, and risks to each life stage.')),
      section('all-sectors','m1.educator.allsectors',b('Abutin ang bawat sektor','Reach every community group'),
        b('Hindi lamang ang mga dumadalo na sa health talk ang kailangang maabot. Pag-isipan kung sino ang hindi nakakasali: mga bata, kabataan, nakatatanda, at iba pang grupo sa barangay. Pumili ng oras, lugar, wika, at paraan na makatutulong sa kanila na makilahok. Magbigay ng impormasyon, kaalaman, at pagkakataong magsanay.',
          'Education must reach beyond people who already attend a health talk. Consider who is missing: children, young people, older adults, and other groups in the barangay. Choose a time, place, language, and format that support participation. Offer information, knowledge, and opportunities to practise.'),
        'audience','A03',[b('Sino ang hindi pa naaabot?','Who is not yet reached?'),b('Anong paraan ang angkop?','What approach will work?')],b('Impormasyon, kaalaman, at pagsasanay para sa bawat sektor.','Information, knowledge, and training for every community group.')),
    ],
    check:check(b('Puro magulang ang dumadalo. Paano mas maaabot ang kabataan?','Only parents attend. How can you better reach young people?'),
      [b('Iangkop ang oras at usapan sa tanong ng kabataan.','Adapt the time and discussion to young people’s questions.'),b('Ulitin ang parehong usapan sa mga magulang lamang.','Repeat the same discussion with parents only.'),b('Ipagpalagay na sapat nang alam nila.','Assume they already know enough.')],0,
      b('Ang pag-angkop sa kausap ay tumutulong maabot ang bawat sektor. Panatilihing aprubado at tama ang impormasyong ibinabahagi.','Adapting to the audience helps reach each group. Keep the information accurate and approved.')),
    takeaway:b('Mabisang pagtuturo: tamang paksa, angkop na paraan, at pagkakataon para sa lahat.','Effective education connects the right topic and approach with opportunities for everyone.'),
  },
  {
    id:'bhw-community-organizer',number:'1.1.3',title:b('Bilang Community Organizer','As a Community Organizer'),minutes:'4–6',
    objective:b('Mailarawan kung paano mag-anyaya ng pakikilahok at magdala ng obserbasyon sa lokal na pagpaplano.','Describe how to invite participation and bring observations into local planning.'),
    sources:'Reference Manual PDF 12; Facilitator Guide PDF 20; Day 1 presentation PDF 10. LIPH elaboration: Reference Manual PDF 12.',
    sections:[
      section('organizer-scene','m1.role.organizer',b('Mula obserbasyon, tungo sa usapan','From observation to conversation'),
        b('Napansin ni Marites ang naipong tubig sa ilang bakuran. Kinausap niya ang mga residente, purok leader, kagawad sa kalusugan, at health staff tungkol sa posibleng sama-samang gawain. Ang Community Organizer ay nagpapanatili ng mabuting relasyon at komunikasyon sa komunidad at sa health staff ng lungsod o munisipyo.',
          'Marites notices standing water in some yards. She talks with residents, the purok leader, the health council member, and health staff about a possible shared activity. A Community Organizer maintains good relationships and communication with the community and city or municipal health staff.'),
        'scene','A01',[b('Mga residente','Residents'),b('Mga lokal na lider','Local leaders'),b('Health staff','Health staff')],b('Ugnayan at komunikasyon ang simula ng sama-samang pagkilos.','Relationships and communication begin collective action.')),
      section('participation','m1.organizer.participation',b('Anyayahang makilahok','Invite people to participate'),
        b('Hindi lang ipinapaalam ni Marites na may clean-up drive. Tinatanong niya kung sino ang makasasama, ano ang kaya nilang gawin, at anong iskedyul ang posible. Ang malinaw na paanyaya ay may gagawin, kasama, at pagkakataong sumagot. Ang mga residente ay kalahok sa gawain, hindi tagapanood lamang.',
          'Marites does more than announce a clean-up drive. She asks who can join, what they can contribute, and which schedule is possible. A clear invitation names an action, includes partners, and allows people to respond. Residents participate rather than simply watch.'),
        'process','A04',[b('Ano ang gagawin?','What will we do?'),b('Sino ang makasasama?','Who can join?'),b('Kailan tayo mag-uusap?','When can we discuss it?')],b('Makinig sa tugon; buuin ang gawain kasama ang mga residente.','Listen to responses; shape the activity with residents.')),
      section('planning-team','m1.organizer.planningteam',b('Dalhin ang nakita sa pagpaplano','Bring observations into planning'),
        b('Inilalarawan ng manual ang BHW bilang bahagi ng barangay planning team for health. Dinadala niya ang kaugnay na obserbasyon upang matulungan ang mga lider na maunawaan at aksyunan ang problema. Ihiwalay ang aktuwal na nakita sa hinala: “May naipong tubig sa tatlong bakuran” ay obserbasyon; hindi pa iyon patunay na iyon ang sanhi ng isang sakit.',
          'The manual describes the BHW as part of the barangay planning team for health. The BHW brings relevant observations to help leaders understand and act on a problem. Separate what was seen from an assumption: “There is standing water in three yards” is an observation; it does not prove the cause of an illness.'),
        'process','A04',[b('Obserbasyon','Observation'),b('Barangay planning team for health','Barangay planning team for health'),b('Napagkasunduang aksyon','Agreed action')],b('Ibahagi ang ebidensya, hindi ang hinalang parang tiyak na katotohanan.','Share evidence without presenting assumptions as established facts.')),
      section('liph','m1.organizer.liph',b('May ambag sa mas malawak na plano','Contribute to wider planning'),
        b('Ang Local Investment Plan for Health o LIPH ay planong pangkalusugan sa antas ng lungsod o probinsya na tinutukoy ng manual. Kinikilala rito ang kontribusyon ng barangay at munisipyo sa pagpaplano. Ang obserbasyong ibinahagi ng BHW ay maaaring makatulong sa pagtalakay ng mga lokal na pangangailangan. Ipaalam sa health team ang ambag sa pamamagitan ng umiiral na lokal na proseso; hindi awtomatikong pondado ang bawat mungkahi.',
          'The Local Investment Plan for Health, or LIPH, is the city or provincial health plan described in the manual. It recognizes barangay and municipal contributions to planning. Observations shared by BHWs can inform discussion of local needs. Contribute through the existing local process with the health team; a proposal does not automatically receive funding.'),
        'process','A04',[b('Pangangailangan sa barangay','Barangay needs'),b('Lokal na pagtalakay','Local discussion'),b('LIPH · lungsod / probinsya','LIPH · city / province')],b('Local Investment Plan for Health: may ambag ang barangay; kumpirmahin ang lokal na proseso.','Local Investment Plan for Health: barangays contribute; confirm the local process.')),
    ],
    check:check(b('Alin ang malinaw na gawaing pang-organisa?','Which is a clear organizing action?'),
      [b('I-post ang plano at huwag nang humingi ng tugon.','Post the plan without inviting responses.'),b('Pangakuan ng pondo ang bawat mungkahi.','Promise funding for every suggestion.'),b('Anyayahan ang residente at health staff na magplano mula sa obserbasyon.','Invite residents and health staff to plan using observations.')],2,
      b('May ugnayan, pakikilahok, at ambag sa pagpaplano. Hindi awtomatikong paglalaan ng pondo ang LIPH link.','This combines relationships, participation, and planning input. The LIPH connection does not guarantee funding.')),
    takeaway:b('Mag-ugnay ng tao, mag-anyaya ng pagkilos, at dalhin ang obserbasyon sa pagpaplano.','Connect people, invite action, and bring observations into planning.'),
  },
  {
    id:'bhw-service-provider',number:'1.1.4',title:b('Bilang Health Service Provider','As a Health Service Provider'),minutes:'4–6',
    objective:b('Matukoy ang angkop na pagtulong, paggabay, at follow-up ayon sa pagsasanay at pangangasiwa.','Identify appropriate assistance, guidance, and follow-up within training and supervision.'),
    sources:'Reference Manual PDF 12; Facilitator Guide PDF 20; Day 1 presentation PDF 11–12.',
    sections:[
      section('first-contact','m1.role.provider m1.provider.firstcontact',b('May residenteng humihingi ng tulong','A resident asks for help'),
        b('Nagtanong si Aling Nena kung saan maaaring makausap ang health worker tungkol sa anak niya. Bilang BHW, maaaring si Marites ang unang lapitan. Bahagi siya ng primary care team ng lungsod o munisipyo at katuwang ng midwife sa barangay. Ang pagiging unang contact ay hindi nangangahulugang siya ang may sagot o paggamot sa lahat.',
          'Aling Nena asks where she can speak with a health worker about her child. As a BHW, Marites may be the first person approached. She is part of the city or municipal primary care team and assists the barangay midwife. Being a first contact does not mean having every answer or providing every treatment.'),
        'scene','A01',[b('Aling Nena · may tanong','Aling Nena · a concern'),b('Marites · unang nilapitan','Marites · first contact'),b('Midwife · katuwang sa team','Midwife · team partner')],b('Bahagi ng primary care team; katuwang ng midwife.','Part of the primary care team; a partner to the midwife.')),
      section('guide','m1.provider.guide',b('Gumabay sa angkop na serbisyo','Guide to an appropriate service'),
        b('Nakikinig si Marites sa pangangailangan at tumutulong tukuyin ang angkop na health worker o pasilidad. Kinukumpirma niya ang lokal na paraan ng paglapit at ipinapaliwanag ang susunod na hakbang. Ang landas sa larawan ay halimbawa ng koordinasyon, hindi sapilitang rutang daraanan ng lahat. Sundin ang lokal na referral at emergency procedures kapag naaangkop.',
          'Marites listens to the need and helps identify an appropriate health worker or facility. She confirms local access arrangements and explains the next step. The pathway illustrates coordination, not a mandatory route for everyone. Follow local referral and emergency procedures when applicable.'),
        'process','A05',[b('Pangangailangan','Need'),b('Angkop na health worker','Appropriate health worker'),b('Malinaw na susunod na hakbang','Clear next step')],b('Halimbawa ng koordinasyon. Sundin ang lokal na referral at emergency procedures.','A coordination example. Follow local referral and emergency procedures.')),
      section('boundaries','m1.provider.initialservices',b('Tumulong ayon sa pagsasanay','Assist within your training'),
        b('Binabanggit ng manual ang pakikipanayam, vital signs, pagtatala, household profiling, at paunang lunas bilang mga halimbawa ng paunang serbisyo. Gawin lamang ang gawaing saklaw ng iyong pagsasanay, lokal na patakaran, at kinakailangang pangangasiwa. Hindi itinuturo rito ang pamamaraan ng pagsukat o paggamot. Kapag hindi tiyak o lampas sa saklaw, humingi ng gabay sa health team.',
          'The manual lists interviewing, vital signs, recording, household profiling, and first aid as examples of initial services. Perform only tasks covered by your training, local policy, and required supervision. This lesson does not teach measurement or treatment procedures. When uncertain or outside your scope, seek guidance from the health team.'),
        'comparison','A05',[b('Pakikipanayam · vital signs · pagtatala','Interviewing · vital signs · recording'),b('Household profile · paunang lunas','Household profile · first aid')],b('Mga halimbawa lamang. Gawin ayon sa pagsasanay, lokal na patakaran, at pangangasiwa.','Examples only. Work within training, local policy, and supervision.')),
      section('follow-up','m1.provider.monitoring',b('May kasunod ang paggabay','Guidance includes follow-up'),
        b('Hindi natatapos ang papel ng BHW sa pagturo kung saan pupunta. Ayon sa tagubilin ng health team, sinusubaybayan niya ang kalagayan, itinatala ang kaugnay na impormasyon, at ipinapaabot ang update sa tamang tao. Kumpirmahin kung ano, kailan, at kanino mag-uulat; huwag mag-imbento ng resulta o mangakong wala nang kailangang follow-up.',
          'The BHW’s role continues after explaining where to go. Following health-team instructions, the BHW monitors the situation, records relevant information, and sends an update to the right person. Confirm what to report, when, and to whom; do not invent an outcome or promise that no further follow-up is needed.'),
        'process','A05',[b('Kumpirmahin ang tagubilin','Confirm the instruction'),b('Subaybayan at itala','Monitor and record'),b('Ibalik ang update sa team','Report back to the team')],b('Ang follow-up ay nagpapatuloy sa ugnayan ng residente at health team.','Follow-up sustains the connection between the resident and health team.')),
    ],
    check:check(b('Humingi ng payong lampas sa iyong pagsasanay ang residente. Ano ang angkop?','A resident asks for advice beyond your training. What is appropriate?'),
      [b('Hulaan ang sagot para hindi siya maghintay.','Guess so the resident will not wait.'),b('Humingi ng gabay sa health team at ipaliwanag ang susunod na hakbang.','Seek health-team guidance and explain the next step.'),b('Sabihing tapos na ang iyong tungkulin.','Say your role is finished.')],1,
      b('Ang paggabay sa angkop na health worker ay pagtulong. Panatilihin ang hangganan ng pagsasanay at sundin ang lokal na tagubilin sa follow-up.','Guiding someone to the appropriate health worker is assistance. Respect training boundaries and follow local follow-up instructions.')),
    takeaway:b('Makinig, tumulong sa loob ng saklaw, gumabay, at mag-follow-up kasama ang health team.','Listen, assist within scope, guide, and follow up with the health team.'),
  },
  {
    id:'bhw-records',number:'1.1.5',title:b('Mga talaan at impormasyon','Records and Information'),minutes:'4–6',
    objective:b('Maitugma ang apat na uri ng talaan sa gamit nito at maipaliwanag kung kanino ihahatid ang kaugnay na impormasyon.','Match four record types to their purposes and explain who should receive relevant information.'),
    sources:'Reference Manual PDF 12; Facilitator Guide PDF 20; Day 1 presentation PDF 5, 12. All sample fields are fictional teaching additions.',
    sections:[
      section('record-purpose','m1.provider.records',b('Saan ginagamit ang tala?','What is the record used for?'),
        b('Tumutulong ang BHW sa pagkolekta at pangangalaga ng impormasyon mula sa mga kabahayang nasasakupan. Ginagamit ang wastong tala sa pagplano ng programa at pagtukoy ng pangangailangan. Ang lahat ng halimbawang dokumento rito ay kathang-isip para sa pag-aaral; hindi sila opisyal na form o aktuwal na patient record.',
          'BHWs help collect and safeguard information from households in their area. Accurate records inform program planning and identification of needs. Every document shown here is a fictional learning example, not an official form or an actual patient record.'),
        'documents','A06',[b('Kolektahin','Collect'),b('Pangalagaan','Safeguard'),b('Gamitin sa pagpaplano','Inform planning')],b('Halimbawang tala lamang · walang tunay na personal na datos.','Learning examples only · no real personal data.')),
      section('household-profile','m1.provider.documents',b('Household profile: isang kabahayan','Household profile: one household'),
        b('Ang household profile ay naglalarawan ng kabahayan. Sa halimbawang ito, code na HH-014 at bilang na apat na miyembro ang ipinapakita upang makita ang uri ng impormasyong pinagsasama. Ang aktuwal na fields at paraan ng pag-iingat ay dapat ayon sa aprubadong lokal na form at tagubilin. Huwag gamitin ang kathang-isip na halimbawa bilang tunay na tala.',
          'A household profile describes a household. This example shows code HH-014 and four members to illustrate the kind of information brought together. Actual fields and storage arrangements must follow the approved local form and instructions. Never use the fictional example as a real record.'),
        'documents','A06',[b('Household profile','Household profile'),b('HH-014 · 4 na miyembro','HH-014 · 4 members')],b('Tanong na sinasagot: ano ang larawan ng kabahayan? Halimbawa lamang.','Question answered: what describes this household? Example only.')),
      section('list-registry','m1.provider.documents',b('Master list o registry?','Master list or registry?'),
        b('Sa paglalarawan ng manual, pinagsasama ng master list ang mga tao ayon sa grupo, gaya ng mga bata, buntis, o nakatatanda. Ang registry naman ay tala ng mga taong nabigyan ng serbisyo. Sa kathang-isip na halimbawa, ang master list ay “grupo: nakatatanda”; ang registry ay “naibigay na serbisyo: health teaching.” Magkaiba ang tanong na sinasagot ng dalawa.',
          'In the manual’s description, a master list groups people, such as children, pregnant residents, or older adults. A registry records people who received services. In this fictional example, the master list says “group: older adults”; the registry says “service provided: health teaching.” They answer different questions.'),
        'documents','A06',[b('Master list · grupo: nakatatanda','Master list · group: older adults'),b('Registry · serbisyo: health teaching','Registry · service: health teaching')],b('Sino ang nasa grupo? / Sino ang nabigyan ng serbisyo? Mga halimbawa lamang.','Who belongs to the group? / Who received a service? Examples only.')),
      section('assigned-form','m1.provider.documents m1.competency',b('Sundin ang tagubilin sa form','Follow the form instructions'),
        b('Maaaring magpagawa ang nurse, midwife, o doktor ng mga form ng gobyerno, DOH, o lokal na pamahalaan. Linawin ang hinihinging impormasyon at tatanggap. Sa halimbawang form, ang field ay “tatanggap: midwife.” Suriin ang pagkakatala laban sa impormasyong nakuha; huwag punan ng hula ang hindi alam. Ihatid at ingatan ang tala ayon sa aprubadong lokal na paraan.',
          'A nurse, midwife, or doctor may assign government, DOH, or local-government forms. Clarify the required information and recipient. The example form highlights “recipient: midwife.” Check entries against the information collected; do not guess missing details. Deliver and safeguard the record using approved local arrangements.'),
        'documents','A06',[b('Assigned form · tatanggap: midwife','Assigned form · recipient: midwife'),b('Suriin · linawin · ihatid','Check · clarify · deliver')],b('Tamang impormasyon sa tamang tatanggap. Halimbawang form lamang.','Accurate information to the appropriate recipient. Sample form only.')),
    ],
    check:check(b('Aling tala ang tumutugon sa “sino ang nabigyan na ng serbisyo”?','Which record answers “who has received a service”?'),
      [b('Household profile','Household profile'),b('Master list ng grupo','Group master list'),b('Registry','Registry')],2,
      b('Registry ang tinutukoy ng manual. Ang master list ay paggrupo ng mga tao; ang household profile ay larawan ng kabahayan. Sundin ang pangalan at gamit ng aprubadong lokal na form.','The manual describes a registry. A master list groups people; a household profile describes a household. Follow the names and purposes of approved local forms.')),
    takeaway:b('Piliin ang tamang tala, tiyakin ang impormasyon, at linawin ang tatanggap.','Choose the appropriate record, verify information, and clarify its recipient.'),
  },
  {
    id:'bhw-roles-application',number:'1.1.6',title:b('Gamitin ang mga tungkulin','Apply the Roles'),minutes:'5–7',
    objective:b('Maipaliwanag ang mga papel na kailangan sa sitwasyon at makapagbigay ng maikling handover ayon sa tagubilin.','Explain the roles needed in a situation and give a short handover following an instruction.'),
    sources:'Reference Manual PDF 11–12; Facilitator Guide PDF 20; Day 1 presentation PDF 5–6, 13. Applied handover is an instructional adaptation.',
    sections:[
      section('applied-observation','m1.competency',b('Isang obserbasyon, maraming hakbang','One observation, several actions'),
        b('Sa kathang-isip na sitwasyon, may naipong tubig sa tatlong bakuran na napuntahan ni Marites. Tagubilin ng midwife: “Itala ang nakita, itanong kung may gustong kausapin ang health team, at iulat sa akin ang kailangan pang aksyon.” Basahin ang tagubilin, linawin ang hindi tiyak, at ihiwalay ang naobserbahan sa hinala. Huwag magbigay ng diagnosis mula sa obserbasyon sa paligid.',
          'In this fictional situation, Marites sees standing water in three yards. The midwife instructs: “Record what you saw, ask whether anyone wants to speak with the health team, and report the actions still needed to me.” Read the instruction, clarify uncertainty, and separate observations from assumptions. Do not diagnose from an environmental observation.'),
        'scene','A07',[b('Nakita: naipong tubig','Observed: standing water'),b('Tatlong bakuran','Three yards'),b('Tagubilin: itala at iulat','Instruction: record and report')],b('Obserbasyon ito; hindi diagnosis o napatunayang sanhi ng sakit.','This is an observation, not a diagnosis or a proven cause of illness.')),
      section('applied-education','m1.role.educator',b('Piliin ang pagtuturong kailangan','Choose the education needed'),
        b('Tatanungin ni Marites kung ano ang gustong linawin ng pamilya tungkol sa kanilang paligid. Gagamit siya ng aprubadong materyal at paliwanag na angkop sa kausap. Sabihin sa sarili mong salita kung paano mo bubuksan ang usapan. Halimbawa: “Ano po ang napapansin ninyo sa tubig na naiipon dito?” Makinig bago magpaliwanag.',
          'Marites asks what the family wants to clarify about their surroundings. She uses approved materials and an explanation suited to the audience. Say in your own words how you would open the conversation. For example: “What have you noticed about the water collecting here?” Listen before explaining.'),
        'scene','A07',[b('Itanong ang alalahanin','Ask about the concern'),b('Gamitin ang aprubadong mensahe','Use an approved message')],b('Health Educator: malinaw na usapang angkop sa pamilya.','Health Educator: a clear conversation suited to the family.')),
      section('applied-organizing','m1.role.organizer m1.organizer.participation',b('Tukuyin ang mga makakatuwang','Identify potential partners'),
        b('Para sa sama-samang gawain, maaaring kausapin ang mga residente at purok leader, kasama ang kagawad at health staff. Magmungkahi ng malinaw na pag-uusap tungkol sa gawain at iskedyul, pagkatapos ay pakinggan ang tugon. Ipaliwanag kung bakit kailangan ang kanilang pakikilahok; ang BHW ay hindi dapat magpasya para sa lahat nang walang usapan.',
          'For a shared activity, talk with residents and the purok leader, together with the council member and health staff. Propose a clear discussion about the activity and schedule, then listen to responses. Explain why their participation matters; the BHW should not decide for everyone without discussion.'),
        'process','A07',[b('Residente + purok leader','Residents + purok leader'),b('Kagawad + health staff','Council member + health staff'),b('Usapan at napagkasunduang gawain','Discussion and agreed action')],b('Community Organizer: anyayahan ang mga tao na magplano at kumilos.','Community Organizer: invite people to plan and act.')),
      section('handover','m1.competency m1.provider.records m1.provider.guide',b('Ihanda ang maikling handover','Prepare a short handover'),
        b('Subukan mong iulat sa midwife: ano ang nakita, ano ang ginawa, at ano ang kailangan pang aksyon. Halimbawa: “May naipong tubig sa tatlong bakuran. Naitala ko ang obserbasyon at nakinig sa tanong ng mga residente. Kailangan kong kumpirmahin sa inyo ang angkop na mensahe at susunod na hakbang.” Itugma ang tala at ulat, sundin ang tagubilin, at ibahagi lamang ang kaugnay na impormasyon sa tamang tatanggap.',
          'Practise reporting to the midwife: what you observed, what you did, and what action is still needed. For example: “There is standing water in three yards. I recorded the observation and listened to residents’ questions. I need to confirm the appropriate message and next step with you.” Keep the record and report consistent, follow the instruction, and share only relevant information with the appropriate recipient.'),
        'handover','A07',[b('Nakita · tubig sa 3 bakuran','Observed · water in 3 yards'),b('Ginawa · itinala at nakinig','Done · recorded and listened'),b('Kailangan · gabay sa susunod na hakbang','Needed · guidance on the next step')],b('Ulat sa midwife: obserbasyon + ginawa + kailangan.','Report to the midwife: observation + action taken + next need.')),
      section('next-learning','m1.skills.crossref',b('Ituloy ang paglinang ng kasanayan','Continue developing your skills'),
        b('Ang 1.1 ay pagpapakilala sa mga papel, hindi patunay na kaya na ang lahat ng gawain. Palalalimin sa 1.6 ang pakikipagkomunikasyon. Iniuugnay ng facilitator guide ang community mobilization sa common competencies at health-promotion teaching sa core competencies. Nasa mga susunod na kabanata ang mga kasanayang iyon; hindi pa available ang Chapters II at III sa prototype. Hiwalay ang obserbasyon ng praktikal na kakayahan sa pagbasa o pagtingin sa slides.',
          'Subchapter 1.1 introduces the roles; it does not establish competence in every task. Subchapter 1.6 develops communication. The facilitator guide links community mobilization to common competencies and health-promotion teaching to core competencies. These skills belong in later chapters; Chapters II and III are not available in this prototype. Practical competence must be observed separately from reading or viewing slides.'),
        'process','A02',[b('1.6 · Komunikasyon','1.6 · Communication'),b('II · Community mobilization','II · Community mobilization'),b('III · Health-promotion teaching','III · Health-promotion teaching')],b('Mga susunod na pag-aaral. Hiwalay na obserbasyon ang praktikal na kakayahan.','Future learning. Practical competence requires separate observation.')),
    ],
    check:check(b('Aling ulat ang sumusunod sa tagubilin nang walang imbentong konklusyon?','Which report follows the instruction without inventing a conclusion?'),
      [b('May tubig sa tatlong bakuran; naitala ko; kailangan ko ng gabay sa susunod na hakbang.','Water in three yards; recorded; I need guidance on the next step.'),b('Tiyak na may sakit na ang lahat doon.','Everyone there is certainly ill.'),b('Wala nang kailangang gawin.','Nothing else needs to be done.')],0,
      b('Naihihiwalay nito ang obserbasyon, nagawa, at kailangan. Bigkasin ang sarili mong handover at ipaliwanag kung paano mo nasunod ang tagubilin; ang pagpili ng sagot ay hindi praktikal na assessment.','It separates observation, action taken, and remaining needs. Speak your own handover and explain how you followed the instruction; selecting an answer is not a practical assessment.')),
    takeaway:b('Maayos na pagkilos: piliin ang papel, sundin ang tagubilin, itala, at makipag-ugnayan.','Sound action: choose the role, follow instructions, record, and communicate.'),
  },
];
