// Fictional Apple adaptation; timing comes from encoded narration samples.
export const SAFETY_IDENTIFY_BEATS = [
 {id:'ana',title_fil:'Tumingin muna',title_en:'Observe first',detail_fil:'Basang pasukan • mainit na ruta',detail_en:'Wet entrance • hot route',fil:'Napansin ni Apple ang basang pasukan at mainit na ruta. Mula sa ligtas na puwesto, kinikilala niya ang panganib.',en:'Apple notices a wet entrance and hot route. From a safe position, she identifies hazards.'},
 {id:'inspect',title_fil:'Apat na field',title_en:'Four fields',detail_fil:'Panganib • pinsala • kontrol • contact',detail_en:'Hazard • harm • control • contact',fil:'Basang sahig: maaaring madulas. Ilayo muna ang tao at humingi ng pagwawasto. Kailangan pang kumpirmahin ang contact.',en:'A wet floor could cause a slip. Keep people away and request correction. The contact still needs confirmation.'},
 {id:'scope-and-contact',title_fil:'Magtanong muna',title_en:'Ask first',detail_fil:'Saklaw at contact: kumpirmahin',detail_en:'Confirm scope and contact',fil:'Itinanong ni Apple kung sino ang aabisuhan at alin ang saklaw ng pagsasanay niya. Hindi siya nag-imbento ng sagot.',en:'Apple asks whom to notify and which tasks are within her training. She does not invent an answer.'},
 {id:'five-hazards',title_fil:'Limang grupo',title_en:'Five groups',detail_fil:'Sharps • impeksyon • strain • stress • aksidente',detail_en:'Sharps • infection • strain • stress • accidents',fil:'Sharps, impeksyon, strain, stress at aksidente: magkaibang panganib ang mga ito. Posibleng pinsala ang pinag-uusapan, hindi diagnosis.',en:'Sharps, infection, strain, stress and accidents are different hazards. These are possible harms, not diagnoses.'},
 {id:'practice',title_fil:'Feedback at retry',title_en:'Feedback and retry',detail_fil:'Hindi sapat ang mag-ingat',detail_en:'Be careful is insufficient',fil:'Sa rehearsal, pinalitan ni Apple ang mag-ingat ng tiyak na ulat. Sinuri ng observer ang apat na field; saka niya inulit.',en:'In rehearsal, Apple replaces be careful with a specific report. The observer checks four fields, then she retries.'},
 {id:'check',title_fil:'Ulat at follow-up',title_en:'Report and follow up',detail_fil:'Contact at pagwawasto: hindi pa tiyak',detail_en:'Contact and correction remain unconfirmed',fil:'Iniulat ni Apple ang basang pasukan, panganib madulas at hinihinging aksyon. Kukumpirmahin niya ang contact at babalikan ang kalagayan. Hindi pa natin alam na naayos na.',en:'Apple reports the wet entrance, slip risk and requested action. She will confirm the contact and follow up. Correction is not yet known.'}
] as const;
